@seriesId = 111803
@seasonNumber = 1

GET {{host}}/series/{{seriesId}}/seasons/{{seasonNumber}}/episodes
Authorization: Bearer {{token}}

###

@episodeNumber = 8

GET {{host}}/series/{{seriesId}}/seasons/{{seasonNumber}}/episodes/{{episodeNumber}}
Authorization: Bearer {{token}}
