@query = "Seinfeld"
@page = 1

GET {{host}}/series/search?q={{query}}&p={{page}}
Authorization: Bearer {{token}}

### GET series by ID

@id = 1400

GET {{host}}/series/{{id}}
Authorization: Bearer {{token}}

### Track series

@userId = 336847c7-a140-4759-8f6f-2576ad264e12
@state = watchlist

POST {{host}}/series/track/{{state}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "{{userId}}",
  "seriesId": "{{id}}"
}

### Untrack series

DELETE {{host}}/users/{{userId}}/series/{{id}}/tracked/{{state}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Get tracked

GET {{host}}/users/{{userId}}/series/tracked/{{state}}
Authorization: Bearer {{token}}