@query = "Twin Peaks"
@show_id = 111803

GET {{tmdb.baseUrl}}/authentication?api_key={{tmdb.apiKey}}

###

GET {{tmdb.baseUrl}}/search/tv?api_key={{tmdb.apiKey}}&query={{query}}

###

GET {{tmdb.baseUrl}}/tv/{{show_id}}?api_key={{tmdb.apiKey}}
