### Authentication

GET {{tmdbBaseUrl}}/authentication?api_key={{tmdbApiKey}}

### Configuration

GET {{tmdbBaseUrl}}/configuration?api_key={{tmdbApiKey}}

### Seach TV

@query = "White lotus"

GET {{tmdbBaseUrl}}/search/tv?api_key={{tmdbApiKey}}&query={{query}}

### Get TV series

@seriesId = 111803

GET {{tmdbBaseUrl}}/tv/{{seriesId}}?api_key={{tmdbApiKey}}

### Get season

@seasonNumber = 3

GET {{tmdbBaseUrl}}/tv/{{seriesId}}/season/{{seasonNumber}}?api_key={{tmdbApiKey}}

### Get episode

@episodeNumber = 1

GET {{tmdbBaseUrl}}/tv/{{seriesId}}/season/{{seasonNumber}}/episode/{{episodeNumber}}?api_key={{tmdbApiKey}}
