@query = "The Office"

GET {{tmdb.baseUrl}}/authentication?api_key={{tmdb.apiKey}}

###

GET {{tmdb.baseUrl}}/search/tv?api_key={{tmdb.apiKey}}&query={{query}}

###

@show_id = 2316

GET {{tmdb.baseUrl}}/tv/{{show_id}}?api_key={{tmdb.apiKey}}
