@userId = bad58664-db23-4490-83b7-f4bda4362c84

POST {{host}}/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### Sign-up

POST {{host}}/users
Content-Type: application/json

{
    "email": "{{email}}",
    "username": "{{username}}",
    "password": "{{password}}"
}

### Update user

PUT {{host}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "changed.email@test.io",
    "username": "changed_username"
}

### Change password

PUT {{host}}/users/{{userId}}/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "{{password}}",
  "newPassword": "ChangedPassword1337"
}

### Delete user

DELETE {{host}}/users/{{userId}}
Authorization: Bearer {{token}}

### Get user

GET {{host}}/users/{{userId}}
Authorization: Bearer {{token}}
